version: 2

project_name: go-vanity-gen

before:
  hooks:
    - go mod download

builds:
  - id: go-vanity-gen
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X krishnaiyer.tech/golang/go-vanity-gen/cmd.version={{.Version}}
      - -X krishnaiyer.tech/golang/go-vanity-gen/cmd.gitCommit={{.Commit}}
      - -X krishnaiyer.tech/golang/go-vanity-gen/cmd.buildDate={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - id: tar
    builds:
      - go-vanity-gen
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    format: tar.gz
  - id: zip
    builds:
      - go-vanity-gen
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
    wrap_in_directory: true
    format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
